  version: "3"

  services:
    mysql:
      image: "mysql:5.7.24"
      container_name: "typeorm-mysql"
      ports:
        - "4242:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "admin"
        MYSQL_USER: "mgw"
        MYSQL_PASSWORD: "yoyo"
        MYSQL_DATABASE: "mgwusers"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_PORT: "3306"
        PMA_HOST: "mysql"
        PMA_USER: "root"
        PMA_PASSWORD: "admin"
      ports:
        - "8181:80"
      restart: always
      depends_on:
        - mysql